version: "3.9"

services:
  booking-service-db:
    container_name: booking-service-db
    image: "mcr.microsoft.com/mssql/server:latest"
    user: root
    ports:
          - "1433:1433"
    environment:
      SA_PASSWORD: "Test12345678!"
      ACCEPT_EULA: "Y"
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"      
    networks:
      - booking-service-app-net
  booking-service-app:
    container_name: booking-service-app
    build: .
    ports:
      - "8001:8001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - booking-service-app-net
    depends_on:
      - booking-service-db
networks:
  booking-service-app-net:
    driver: bridge
    attachable: true
